# Generated by Django 4.2.20 on 2025-03-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"verbose_name_plural": "Log entries"},
        ),
        migrations.AlterField(
            model_name="logentry",
            name="activity",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
